### ISSUE TITLE
Unable to create \ work with .NET Core projects

### ISSUE THREAD

**Issue by DjoleDzele** [consulo/incubating-consulo-dotnet-core#5]
- IDE build number: 2483 (Version 2020.2)
- Java version: openjdk 10.0.2 2018-07-17
- OS name and version: Manjaro Linux

When choosing to create new project in C#, I can only select .NET Mono SDK and not .NET Core, even though i added Core paths in settings?

![Screenshot_20200414_153251](https://user-images.githubusercontent.com/48789138/79231546-861c7f80-7e66-11ea-9097-9230b52df55b.png)
![Screenshot_20200414_153344](https://user-images.githubusercontent.com/48789138/79231548-874dac80-7e66-11ea-9832-cd636af88bcc.png)

**Comment by VISTALL** [comment]
Hello. This issue in progress already by new MSBuild implementation. 

You can track it by https://github.com/orgs/consulo/projects/19

**Comment by VISTALL** [comment]
Added import .NET projects, also running too
