### ISSUE TITLE
Dependencies doesn't load

### ISSUE THREAD

**Issue by Zeon8** [consulo/incubating-consulo-dotnet-core#7]
When I create new .net core 3.1 or .net 5 and open it with Consulo, autocomplete doesn't work properly and there is no dependencies in list.
Here is screenshot:
![image](https://user-images.githubusercontent.com/39654434/115586364-2d7f8e00-a2d5-11eb-9fc0-c7a471de461f.png)

Consulo:
  version = 2021.4
  build number = 2882
  build date = April 9, 2021
 Plugins:
  com.intellij = 2882
  com.intellij.regexp = 1254
  com.intellij.spellchecker = 1261
  com.intellij.xml = 2731
  com.intellij.properties = 2834
  consulo.dotnet = 3409
  consulo.dotnet.microsoft = 4013
  consulo.dotnet.mono = 4026
  consulo.csharp = 5047
  consulo.dotnet.core = 6520
  consulo.javascript = 3193
  consulo.library.batik = 557
  com.intellij.images = 2023
  consulo.library.flexmark = 557
  com.intellij.tasks = 4710
  consulo.msbuild = 4421
  consulo.nuget = 4546
  consulo.nunit = 4562
  consulo.opencover = 3375
  consulo.platform.desktop = 2882
  org.jetbrains.plugins.github = 4456
  org.jetbrains.plugins.yaml = 2198

**Comment by VISTALL** [comment]
Hello. While importing Consulo show Log of msbuild. Can you show it?

**Comment by Zeon-4** [comment]
No, because Log doesn't show. I tried to find where it could be shown.
Only found this in consulo.log:
```
[ 312385]   WARN - pl.network.MSBuildServerThread - Interrupted function call: accept failed 
java.net.SocketException: Interrupted function call: accept failed
	at java.net.PlainSocketImpl.accept0(Native Method) ~[?:?]
	at java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:159) ~[?:?]
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458) ~[?:?]
	at java.net.ServerSocket.implAccept(ServerSocket.java:565) ~[?:?]
	at java.net.ServerSocket.accept(ServerSocket.java:533) ~[?:?]
	at consulo.msbuild.daemon.impl.network.MSBuildServerThread.run(MSBuildServerThread.java:61) [MSBuildTreeStructureGetDataRule.class:?]
```

**Comment by VISTALL** [comment]
Can you attach full log? (or send me via email)

**Comment by Zeon-4** [comment]
Yes, here is: [consulo.log](https://github.com/consulo/incubating-consulo-dotnet-core/files/6352835/consulo.log)

**Comment by VISTALL** [comment]
It's just project opening. Can you attach log after opening and click on Refresh button from MSBuild window here

![image](https://user-images.githubusercontent.com/542934/115607301-7c392200-a2ed-11eb-84ea-8e89f6378133.png)

**Comment by VISTALL** [comment]
Can you say your OS version, dotnet --version too.

**Comment by Zeon-4** [comment]
OS: Window 10 1809 LTSC 
dotnet: 5.0.102

**Comment by VISTALL** [comment]
Hello. Tested. There some instructions. (my bad need make it more clear). 

prepare
* Switch to nightly(https://consulo.help/platform/update_channels/) 
* Call Check for Updates
* enable Settings -> Platform and Plugins -> Experimental Features -> Experimental Plugins 
* Goto Settings -> Platform and Plugins -> From Repository (click refresh)
* Find plugin **.NET (....)** and install it

![](https://klikr.org/3842f697a809bd7a7aaf8e53fc28.png)

drop .consulo dir from .

When you try to open .csproj file you will see like this:

![](https://klikr.org/f657b5d71c784b5a804e90bd8534.png)

if not - write here.

Thanks
